export const authTypes = {
	REGISTER_REQUEST: "REGISTER_REQUEST",
	REGISTER_SUCCESS: "REGISTER_SUCCESS",
	REGISTER_FAILURE: "REGISTER_FAILURE",

	LOGIN_REQUEST: "LOGIN_REQUEST",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAILURE: "LOGIN_FAILURE",

	LOGOUT_REQUEST: "LOGOUT_REQUEST",
	LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
	LOGOUT_FAILURE: "LOGOUT_FAILURE",

	
};

export const profileTypes={
	USER_UPDATE_REQUEST: "USER_UPDATE_REQUEST",
	USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
	USER_UPDATE_FAILURE: "USER_UPDATE_FAILURE",

}


export const postTypes = {
	CREATE_POST_REQUEST: "CREATE_POST_REQUEST",
	CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
	CREATE_POST_FAILURE: "CREATE_POST_FAILURE",

	EDIT_POST_REQUEST: "EDIT_POST_REQUEST",
	EDIT_POST_SUCCESS: "EDIT_POST_SUCCESS",
	EDIT_POST_FAILURE: "EDIT_POST_FAILURE",

	DELETE_POST_REQUEST: "DELETE_POST_REQUEST",
	DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
	DELETE_POST_FAILURE: "DELETE_POST_FAILURE",

	REDIRECT_TRUE: "REDIRECT_TRUE",
	REDIRECT_FALSE: "REDIRECT_FALSE",

	GET_USER_POST_REQUEST: "GET_USER_POST_REQUEST",
	GET_USER_POST_SUCCESS: "GET_USER_POST_SUCCESS",
	GET_USER_POST_FAILURE: "GET_USER_POST_FAILURE",

	GET_SINGLE_POST_REQUEST: "GET_SINGLE_POST_REQUEST",
	GET_SINGLE_POST_SUCCESS: "GET_SINGLE_POST_SUCCESS",
	GET_SINGLE_POST_FAILURE: "GET_SINGLE_POST_FAILURE",

	SET_ERRORS_EMPTY: "SET_ERRORS_EMPTY",
};


export const userTypes = {
	GET_SINGLE_POST_REQUEST: "GET_SINGLE_POST_REQUEST",
	GET_SINGLE_POST_SUCCESS: "GET_SINGLE_POST_SUCCESS",
	GET_SINGLE_POST_FAILURE: "GET_SINGLE_POST_FAILURE",

	GET_POSTS_REQUEST: "GET_POSTS_REQUEST",
	GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
	GET_POSTS_FAILURE: "GET_POSTS_FAILURE",
};